### ISSUE TITLE
[RFE] Use Erlang 19 new UNIX socket if available

### ISSUE THREAD

**Issue by lemenkov** [systemd/erlang-sd_notify#1]

**Comment by Gsantomaggio** [comment]
Tired to rebuild the package with `Erlang 19` and I got this error:

```
==> sd (compile)

=ERROR REPORT==== 4-Jul-2016::13:39:33 ===
Error in process <0.36.0> with exit value:
{{case_clause,[]},
 [{code_server,split_base,1,[{file,"code_server.erl"},{line,639}]},
  {code_server,archive_subdirs,1,[{file,"code_server.erl"},{line,825}]},
  {code_server,do_insert_name,3,[{file,"code_server.erl"},{line,819}]},
  {code_server,do_add,4,[{file,"code_server.erl"},{line,739}]},
  {code_server,add_path,4,[{file,"code_server.erl"},{line,714}]},
  {code_server,handle_call,3,[{file,"code_server.erl"},{line,255}]},
  {code_server,loop,1,[{file,"code_server.erl"},{line,150}]}]}
2016-07-04 13:39:34 std_info
    application:     exited:     type: kernel
```

I am trying to understand why

**Comment by Gsantomaggio** [comment]
using `rebar3` seems to work better. But it needs some work to do

**Comment by Gsantomaggio** [comment]
@lemenkov added the docker for Erlang 19.0, let me know if it is enough to close the issue, maybe we can release the binaries build with 18.3 and 19.0.

**Comment by hauleth** [comment]
I have written something [similar in pure Erlang](https://github.com/hauleth/erlang-systemd). There are plans to offer more systems functionalities.

**Comment by weiss** [comment]
Hah, FWIW, I was going to suggest something similar as well, except [my go at it][1] keeps the socket in the `gen_server` state rather than reopening it on each notification (and uses the normal `gen_server` timeout for triggering watchdog notifications) …

[1]: https://gist.github.com/weiss/8ee73f83cbe27417e3863c72d00e45b9

**Comment by hauleth** [comment]
@weiss this is exactly the same approach I have taken with my `systemd` library (which is available via Hex by the way).
