### ISSUE TITLE
[RFE] Add sd_pid_notify/sd_pid_notifyf

### ISSUE THREAD

**Issue by lemenkov** [systemd/erlang-sd_notify#2]

**Comment by Gsantomaggio** [comment]
WIP here https://github.com/systemd/erlang-sd_notify/tree/erlang-sd_notify-2

**Comment by Gsantomaggio** [comment]
@lemenkov since I am on this branch what do you think to add also `sd_pid_notify_with_fds`?

**Comment by lemenkov** [comment]
Cool!

@Gsantomaggio regarding sd_pid_notify_with_fds - I think it's better to propose it in a separate PR. I have a gut feeling this might be more complicated than these two.

**Comment by Gsantomaggio** [comment]
@lemenkov yes I agree!
