### ISSUE TITLE
Erlang 21

### ISSUE THREAD

**Issue by Gsantomaggio** [systemd/erlang-sd_notify#28]
Hi @lemenkov,

Should we rebuild and setup it also for Erlang 21 ?

**Comment by lemenkov** [comment]
@Gsantomaggio certainly! Thanks for the heads up. Does Travis-Ci already support Erlang 21?

**Comment by lemenkov** [comment]
Oh, I've just found - we didn't add Erlang 20 to our Travis-CI setup either.

**Comment by Gsantomaggio** [comment]
We don't care too much about what Travis-Ci  supports, we are using [Docker](https://github.com/systemd/erlang-sd_notify/blob/master/.travis.yml#L10) on Travis.

Will add both
