### ISSUE TITLE
CI with Travis.

### ISSUE THREAD

**Issue by lemenkov** [systemd/erlang-sd_notify#9]
This tiny library should be tested with Travis-CI.

**Comment by Gsantomaggio** [comment]
@lemenkov I tried with my account but I don't have the permissions.

**Comment by lemenkov** [comment]
@Gsantomaggio interesting, but sd_pid_notify/sd_pid_notifyf are available only since systemd v. 214 which is too new for ubuntu 12.04 and ubuntu 14.04 available in Travis-CI

https://travis-ci.org/lemenkov/erlang-sd_notify/builds/141628283

**Comment by Gsantomaggio** [comment]
@lemenkov I am experimenting to use `Docker` on Travis.
https://travis-ci.org/Gsantomaggio/erlang-sd_notify/builds/141733988 
I am not totally sure can work.

**Comment by Gsantomaggio** [comment]
Ok seems to work.
It is not properly elegant, but [here](https://travis-ci.org/Gsantomaggio/erlang-sd_notify/builds/141802241) I put an error and is marked as failed , and[ here](https://travis-ci.org/Gsantomaggio/erlang-sd_notify/builds/141802770) I fixed it and the build is ok. 

Or we can just wait that travis update the machines :)!

**Comment by lemenkov** [comment]
@Gsantomaggio cool! squash all commits and propose a PR !
